title: digits | Go-to Contact Management App
description: A template for quickly starting Meteor application development
google_analytics:
show_downloads: true
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
